package com.example.personalmemoryai.database

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Binary vector representation generated by an ML model.
 *
 * The actual vector is stored as Float32 bytes through
 * DatabaseConverters.
 *
 * An embedding is a mathematical representation of visual
 * characteristics. It is not itself a person's name or identity.
 */
@Entity(
    tableName = "embeddings",
    indices = [
        Index(value = ["ownerType", "ownerId"]),
        Index(value = ["modelName", "modelVersion"]),
        Index(value = ["dimension"])
    ]
)
data class EmbeddingEntity(

    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Type of object represented by this embedding.
     *
     * Examples:
     * FACE
     * IMAGE
     * OBJECT
     */
    val ownerType: String,

    /**
     * ID of the associated entity.
     *
     * For FACE this is FaceEntity.id.
     */
    val ownerId: Long,

    /**
     * Embedding vector.
     */
    val vector: FloatArray,

    /**
     * Number of dimensions in the vector.
     */
    val dimension: Int,

    /**
     * Model that generated the vector.
     */
    val modelName: String,

    /**
     * Exact model version.
     */
    val modelVersion: String,

    /**
     * Whether vector was normalized.
     */
    val normalized: Boolean = true,

    /**
     * Creation timestamp.
     */
    val createdAt: Long = System.currentTimeMillis()
)
