package com.example.personalmemoryai.indexing

object ObjectLabelCatalog {
    private val arabic = mapOf(
        "person" to "شخص|رجل|امرأة|إنسان",
        "bicycle" to "دراجة",
        "car" to "سيارة",
        "motorcycle" to "دراجة نارية",
        "airplane" to "طائرة",
        "bus" to "حافلة|باص",
        "train" to "قطار",
        "truck" to "شاحنة",
        "boat" to "قارب",
        "bird" to "طائر|عصفور",
        "cat" to "قطة|قط",
        "dog" to "كلب",
        "horse" to "حصان",
        "cow" to "بقرة",
        "elephant" to "فيل",
        "bear" to "دب",
        "backpack" to "حقيبة ظهر",
        "handbag" to "حقيبة يد",
        "suitcase" to "حقيبة سفر",
        "bottle" to "زجاجة|قنينة",
        "cup" to "كوب|فنجان",
        "fork" to "شوكة",
        "knife" to "سكين",
        "spoon" to "ملعقة",
        "bowl" to "وعاء|صحن",
        "banana" to "موزة|موز",
        "apple" to "تفاحة|تفاح",
        "orange" to "برتقالة|برتقال",
        "pizza" to "بيتزا",
        "cake" to "كعكة|كيك",
        "chair" to "كرسي",
        "couch" to "أريكة|كنبة",
        "potted plant" to "نبتة|نبات",
        "bed" to "سرير",
        "dining table" to "طاولة|مائدة",
        "toilet" to "مرحاض|حمام",
        "tv" to "تلفاز|تلفزيون",
        "laptop" to "حاسوب محمول|لابتوب",
        "mouse" to "فأرة|ماوس",
        "keyboard" to "لوحة مفاتيح",
        "cell phone" to "هاتف|جوال|هاتف محمول",
        "book" to "كتاب",
        "clock" to "ساعة",
        "vase" to "مزهرية",
        "teddy bear" to "دب محشو|دمية دب",
        "toothbrush" to "فرشاة أسنان"
    )

    fun arabicAliases(label: String): String = arabic[label] ?: ""
}
