package com.example.personalmemoryai.semantic

import android.content.Context
import android.net.Uri
import com.example.personalmemoryai.database.AppDatabase
import com.example.personalmemoryai.database.EmbeddingEntity
import com.example.personalmemoryai.database.ImageEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Local image-to-image semantic retrieval using the imported MobileCLIP-S2 FP16 model.
 * Text encoding intentionally remains deferred behind TextEncoder.
 */
class SemanticSearchService(context: Context) : AutoCloseable {

    private val appContext = context.applicationContext
    private val database = AppDatabase.getInstance(appContext)
    private val modelManager = MobileClipModelManager(appContext)
    private val encoder = MobileClipImageEncoder(appContext, modelManager)

    suspend fun ensureModel() {
        if (!modelManager.isInstalled()) {
            throw IllegalStateException("لم يتم استيراد نموذج MobileCLIP-S2 بعد")
        }
        check(encoder.load()) { "تعذر تحميل نموذج MobileCLIP-S2" }
    }

    suspend fun importModel(source: Uri, onProgress: (Long, Long) -> Unit = { _, _ -> }) {
        modelManager.importModel(source, onProgress)
        encoder.close()
    }

    fun isModelInstalled(): Boolean = modelManager.isInstalled()

    fun modelSizeBytes(): Long = modelManager.installedSizeBytes()

    suspend fun imageEmbeddingCount(): Long = withContext(Dispatchers.IO) {
        database.embeddingDao().countByOwnerType(MobileClipImageEncoder.OWNER_TYPE)
    }

    /**
     * Builds the persistent visual index for all currently indexed images.
     * Existing embeddings generated by the same MobileCLIP model/version are reused.
     */
    suspend fun indexAllImages(
        onProgress: (processed: Int, total: Int, embedded: Int, skipped: Int) -> Unit = { _, _, _, _ -> }
    ) = withContext(Dispatchers.Default) {
        ensureModel()
        val images = database.imageDao().getAll()
        val total = images.size
        var processed = 0
        var embedded = 0
        var skipped = 0

        for (image in images) {
            try {
                val existing = database.embeddingDao().getForOwnerAndModel(
                    MobileClipImageEncoder.OWNER_TYPE,
                    image.id,
                    MobileClipImageEncoder.MODEL_NAME,
                    MobileClipImageEncoder.MODEL_VERSION
                )
                if (existing != null) {
                    skipped++
                } else {
                    indexImageAndStore(image)
                    embedded++
                }
            } catch (t: Throwable) {
                t.printStackTrace()
            } finally {
                processed++
                onProgress(processed, total, embedded, skipped)
            }
        }
    }

    suspend fun indexImage(image: ImageEntity): EmbeddingEntity = withContext(Dispatchers.Default) {
        ensureModel()
        val vector = encoder.encode(Uri.parse(image.uri))
        EmbeddingEntity(
            ownerType = MobileClipImageEncoder.OWNER_TYPE,
            ownerId = image.id,
            vector = vector,
            dimension = vector.size,
            modelName = MobileClipImageEncoder.MODEL_NAME,
            modelVersion = MobileClipImageEncoder.MODEL_VERSION,
            normalized = true
        )
    }

    suspend fun indexImageAndStore(image: ImageEntity): Long {
        val embedding = indexImage(image)
        database.embeddingDao().deleteForOwner(embedding.ownerType, embedding.ownerId)
        return database.embeddingDao().insert(embedding)
    }

    suspend fun searchSimilarImages(queryUri: Uri, limit: Int = 30): List<ScoredImage> =
        withContext(Dispatchers.Default) {
            ensureModel()
            val query = encoder.encode(queryUri)
            val embeddings = database.embeddingDao().getAllForImageSearch()
            val results = ArrayList<ScoredImage>(embeddings.size)
            val imageIds = embeddings.map { it.ownerId }.distinct()
            val images = database.imageDao().getByIds(imageIds).associateBy { it.id }

            for (embedding in embeddings) {
                if (embedding.modelName != MobileClipImageEncoder.MODEL_NAME ||
                    embedding.modelVersion != MobileClipImageEncoder.MODEL_VERSION ||
                    embedding.dimension != query.size
                ) continue
                val image = images[embedding.ownerId] ?: continue
                val score = cosine(query, embedding.vector)
                results += ScoredImage(image, score)
            }
            results.sortedByDescending { it.score }.take(limit)
        }

    private fun cosine(a: FloatArray, b: FloatArray): Float {
        var dot = 0.0
        var normA = 0.0
        var normB = 0.0
        val size = minOf(a.size, b.size)
        for (i in 0 until size) {
            dot += a[i].toDouble() * b[i].toDouble()
            normA += a[i].toDouble() * a[i].toDouble()
            normB += b[i].toDouble() * b[i].toDouble()
        }
        if (normA == 0.0 || normB == 0.0) return 0f
        return (dot / (kotlin.math.sqrt(normA) * kotlin.math.sqrt(normB))).toFloat()
    }

    data class ScoredImage(val image: ImageEntity, val score: Float)

    override fun close() = encoder.close()
}
